Numpy is a linear algebra library for python

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Numpy arrys are essentially comes in two flavours : vectors and matrices

*** Vectors are strictly 1-d array and matices are 2-d and some time there can be only one row/ column in it ***

In [2]:
# Numpy Arrays
my_list =[1,2,3,4]

In [4]:
import numpy as np

# we are converting a list into an array by using np.array() method by passing list as an argument and it will
# return an array
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [30]:
# as similar to range function, here in numpy we have arange() function 

arr = np.arange(0,10,1)

In [36]:
#  reshape is used to convert or reshape a 1 d array to matrix of given size
# arr
arr_new = arr.reshape(2,5)
arr_new

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
# there are some deicated methods to get an array of zeros and ones as follows

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3)) # here the 1st argument indicates rows and 2 nd indicates columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# linspace gives evenly spaces values of the given range as follows

np.linspace(0,10,20) # 1st arg is start, 2 nd arg is end , 3 rd is how many evenly spaced values needed between 1st and 2 nd arg


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
# Create Identity Matrix
np.eye(4) # 4 is the matrix size


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Create a random matrix of 0 to 1 distribution
np.random.rand(4)

array([0.27968989, 0.08980428, 0.99776521, 0.42036476])

In [18]:
# Create a random matrix of any number  distribution
np.random.randn(4)

array([-0.69942238, -1.41045498,  1.68727925, -0.94955969])

In [22]:
# return a set of random numbers from a given range
np.random.randint(1,20,5) # 1st arg is starting number inclusive, 2 arg is exclusive, no.of values required from range of 1st and 2nd arg


array([2, 4, 2, 8, 9])

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)
ranarr

array([46, 10,  7,  2,  0,  8,  8, 46, 27, 45])

In [31]:
print(ranarr.max())
print(ranarr.min())
# get max value, min

46
0


In [32]:
#  to get the index of the max and min we use below methods

print( ranarr.argmax())
print(ranarr.argmin())

0
4


In [33]:
#  to check the datatype of the array we use dtype
arr.dtype

dtype('int64')

# Numpy indexing and selction

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:4]

array([0, 1, 2, 3])

In [6]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
#  bread casting, means it will set the value which we are assigning to the position that we are giving in the slicing as follows
arr[0:5] = 200

In [8]:
arr

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#  here we are witnessing a change in the orginal array even in if we changed the another array of sliced part
slice_of_arr =  arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [11]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr_copy = arr.copy()
arr_copy[:] = 100

In [21]:
#  above we made a copy of the existing array is we make any change in the copy it won't effect the original array
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [22]:
list = [[27,48,92],[28,56,49],[10,30,47]]  
array_new = np.array(list)
array_new

array([[27, 48, 92],
       [28, 56, 49],
       [10, 30, 47]])

In [23]:
array_new[2,1]

30

In [26]:
# slicing the matix

array_new[:2,:2]


array([[27, 48],
       [28, 56]])

In [37]:
#  Conditonal selection
array = np.arange(10)

array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#  it returns a matrix of boolen value wherever it is matching with the condition
boolean_arr = array>5
# boolean_arr

In [40]:
boolean_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [41]:
array[boolean_arr]

array([6, 7, 8, 9])

In [42]:
array[array<5]

array([0, 1, 2, 3, 4])

# Numpy Operations
 .Array witha array
 .Array with scalars
 .Universal Array Functions

In [43]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#  adding 2 arrays
array+array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
array*array


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
#  we can do operation by element by element
array+100   # this will add 100 to each element in the array


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])